"use client";
import moment from "moment";
import Head from "next/head";
import Img from "next/image";
import { useRouter } from "next/router";
import React, { useCallback, useEffect, useState } from "react";
import Web3 from "web3";
import Navbar from "../../components/Navbar";
import { useData } from "../../contexts/DataContext";

export interface MarketProps {
  id: string;
  title: string;
  imageHash: string;
  totalAmount: number;
  totalYes: number;
  totalNo: number;
  description: string;
  titleA: string;
  titleB: string;
  settled: boolean;
}

const Details = () => {
  const router = useRouter();
  const { id } = router.query;
  const { polymarket, account, loadWeb3, loading, getBetData } = useData();
  const [market, setMarket] = useState<MarketProps>();
  const [selected, setSelected] = useState<string>("YES");
  const [dataLoading, setDataLoading] = useState(true);
  const [button, setButton] = useState<string>("Trade");

  const [input, setInput] = useState("");

  const getMarketData = useCallback(async () => {
    const betData = await getBetData(parseInt(id as string));
    console.log("betData222", betData);
    setMarket({
      id: id as string,
      title: betData.title,
      imageHash: "aabbcc",
      totalAmount: betData.currentTotalAAmount + betData.currentTotalBAmount,
      totalYes: betData.currentTotalAAmount,
      totalNo: betData.currentTotalBAmount,
      description: "foo description",
      titleA: betData.optionATitle,
      titleB: betData.optionBTitle,
      settled: betData.closed,
    });
    setDataLoading(false);
    if (betData.closed) {
      setButton("Already Settled With Outcome: " + (betData.aWon ? "A" : "B"));
    }
  }, [account, id, polymarket]);

  const handleSettle = async (option: string) => {
    setButton("Please wait");
    setDataLoading(true);
    try {
      const receipt = await polymarket.methods
        .settle(parseInt(id as string), option === "a")
        .send({
          from: account,
          gas: 2000000, // Set an appropriate gas limit
        });
      console.log("Receipt: ", receipt);
      await getMarketData();
    } catch (err: any) {
      alert("Error settling:" + err.toString());
    } finally {
      setDataLoading(false);
    }
  };
  const handleTrade = async () => {
    setButton("Please wait");
    setDataLoading(true);
    try {
      if (Number.isNaN(parseInt(input)) || parseFloat(input) <= 0) {
        throw new Error("Invalid input");
      }
      const inputWei = Web3.utils.toWei(input, "ether");
      if (selected === "YES") {
        const receipt = await polymarket.methods.bet(id, true).send({
          from: account,
          value: inputWei,
          gas: 2000000, // Set an appropriate gas limit
        });
        console.log("Receipt: ", receipt);
      } else if (selected === "NO") {
        const receipt = await polymarket.methods.bet(id, false).send({
          from: account,
          value: inputWei,
          gas: 2000000, // Set an appropriate gas limit
        });
        console.log("Receipt: ", receipt);
      }
      await getMarketData();
    } catch (err: any) {
      alert("Error trading:" + err.toString());
    } finally {
      setButton("Trade");
      setDataLoading(false);
    }
  };

  useEffect(() => {
    loadWeb3();
  }, [loading]);

  useEffect(() => {
    if (polymarket) {
      getMarketData();
    }
  }, [polymarket]);

  return (
    <div className="flex flex-col justify-center items-center h-full">
      <Head>
        <title>Polymarket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="w-full flex flex-col sm:flex-row py-4 max-w-5xl">
        {dataLoading || loading ? (
          <div className="flex flex-col justify-center items-center h-full w-full pt-10">
            <div className="text-center">
              <div className="text-3xl font-bold">Loading...</div>
            </div>
          </div>
        ) : (
          <div className="w-full flex flex-col pt-1">
            <div className="p-6 rounded-lg flex flex-row justify-start border border-gray-300">
              <div className="flex flex-row">
                <div className="h-w-15 pr-4">
                  {market?.imageHash && market?.imageHash.length > 7 ? (
                    <Img
                      src={`${market?.imageHash}`}
                      className="rounded-full"
                      width={55}
                      height={55}
                    />
                  ) : null}
                </div>
                <div className="flex flex-col justify-start w-1/2 space-y-1">
                  <span className="text-xs font-light text-gray-500 whitespace-nowrap">
                    Title:
                  </span>
                  <span className="text-lg font-semibold whitespace-nowrap">
                    {market?.title}
                  </span>
                </div>
              </div>
              <div className="flex flex-row items-center space-x-4 ml-3">
                <div className="flex flex-col justify-start bg-gray-100 p-3">
                  <span className="text-xs font-light text-gray-500 whitespace-nowrap">
                    Total Volume
                  </span>
                  <span className="text-base font-semibold text-black whitespace-nowrap">
                    {Web3.utils.fromWei(
                      market?.totalAmount.toString() ?? "0",
                      "ether"
                    ) ?? 0}{" "}
                    ETH
                  </span>
                </div>
              </div>
            </div>
            <div className="flex flex-col space-y-3">
              <div className="w-full flex flex-row mt-5">
                <div className="w-2/3 border rounded-lg p-1 pb-4 border-gray-300 mr-2">
                  CHART HERE
                </div>
                <div className="w-1/3 rounded-lg border border-gray-300 ml-2">
                  <div className="flex flex-col items-start p-6">
                    <span className="text-lg font-bold m-auto pb-2">Buy</span>
                    <hr className="text-black w-full py-2" />
                    <span className="text-base">Pick Outcome</span>
                    <div
                      className={`w-full py-2 px-2 ${
                        selected == "YES"
                          ? "bg-green-500 text-white"
                          : "bg-gray-100"
                      } mt-2 cursor-pointer`}
                      onClick={() => setSelected("YES")}
                    >
                      <span className="font-bold">{market?.titleA}</span>{" "}
                      {!market?.totalAmount
                        ? `0`
                        : (
                            (market?.totalYes * 100) /
                            market?.totalAmount
                          ).toFixed(2)}
                      %{"    ( "}
                      {Web3.utils.fromWei(
                        market?.totalYes.toString() ?? "0",
                        "ether"
                      ) ?? 0}
                      {" ETH)"}
                    </div>
                    <div
                      className={`w-full py-2 px-2 ${
                        selected == "NO"
                          ? "bg-green-500 text-white"
                          : "bg-gray-100"
                      } mt-2 cursor-pointer`}
                      onClick={() => setSelected("NO")}
                    >
                      <span className="font-bold">{market?.titleB}</span>{" "}
                      {!market?.totalAmount
                        ? `0`
                        : (
                            (market?.totalNo * 100) /
                            market?.totalAmount
                          ).toFixed(2)}
                      %{"    ( "}
                      {Web3.utils.fromWei(
                        market?.totalNo.toString() ?? "0",
                        "ether"
                      ) ?? 0}
                      {" ETH)"}
                    </div>
                    <span className="text-sm mt-5 mb-4">How much?</span>
                    <div className="w-full border border-gray-300 flex flex-row items-center">
                      <input
                        type="search"
                        name="q"
                        value={input}
                        onChange={(e) => setInput(e.target.value)}
                        className="w-full py-2 px-2 text-base text-gray-700 border-gray-300 rounded-md focus:outline-none"
                        placeholder="0"
                        autoComplete="off"
                      />
                      <span className="whitespace-nowrap text-sm font-semibold">
                        ETH |{" "}
                      </span>
                      <span className="text-sm font-semibold text-blue-700 mx-2 underline cursor-pointer">
                        Max
                      </span>
                    </div>
                    <button
                      className={`mt-5 rounded-lg py-3 text-center w-full ${
                        market?.settled ? "bg-gray-700" : "bg-blue-700"
                      } text-white`}
                      onClick={handleTrade}
                      disabled={button !== "Trade"}
                    >
                      {button}
                    </button>
                  </div>
                </div>
              </div>
              <div className="w-2/3 flex flex-col">
                <button
                  className={`mt-5 rounded-lg py-3 text-center w-full ${
                    market?.settled ? "bg-gray-700" : "bg-blue-700"
                  } text-white`}
                  onClick={() => handleSettle("a")}
                  disabled={market?.settled}
                >
                  Settle A
                </button>
              </div>
              <div className="w-2/3 flex flex-col">
                <button
                  className={`mt-5 rounded-lg py-3 text-center w-full ${
                    market?.settled ? "bg-gray-700" : "bg-blue-700"
                  } text-white`}
                  onClick={() => handleSettle("b")}
                  disabled={market?.settled}
                >
                  Settle B
                </button>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default Details;
